import { supabase } from './supabase'
const apiBase=(import.meta.env.VITE_R2_UPLOAD_API as string|undefined)?.trim().replace(/\/$/,'')
export interface ChannelConnectionAdmin{channelKey:string;connectionKey:string;label:string;externalAccountId?:string|null;status:string;hasCredentials:boolean;lastSyncedAt?:string|null;lastError?:string|null;activationStatus?:string;environment?:string;verifiedAt?:string|null;testPublishAt?:string|null}
async function call<T>(path:string,init:RequestInit={}):Promise<T>{if(!apiBase||!supabase)throw new Error('Backend not configured');const {data}=await supabase.auth.getSession();if(!data.session)throw new Error('Session หมดอายุ');const r=await fetch(apiBase+path,{...init,headers:{authorization:'Bearer '+data.session.access_token,...(init.body?{'content-type':'application/json'}:{}),...(init.headers||{})}});const j=await r.json().catch(()=>({})) as any;if(!r.ok)throw new Error(j.error||('API '+r.status));return j}
export async function listChannelConnections(){return (await call<{connections:ChannelConnectionAdmin[]}>('/commerce/channel-connections')).connections}
export async function saveChannelCredentials(channelKey:string,connectionKey:string,credentials:Record<string,string>){return call('/commerce/channel-connections/credentials',{method:'POST',body:JSON.stringify({channelKey,connectionKey,...credentials})})}
export async function disconnectChannel(channelKey:string,connectionKey:string){return call('/commerce/channel-connections/disconnect',{method:'POST',body:JSON.stringify({channelKey,connectionKey})})}

export async function startChannelAuthorization(channelKey:string,connectionKey:string){return call<{authorizationUrl:string}>('/commerce/channel-connections/authorize',{method:'POST',body:JSON.stringify({channelKey,connectionKey})})}
export async function testChannelConnection(channelKey:string,connectionKey:string){return call<{ok:boolean;identity?:Record<string,unknown>}>('/commerce/channel-connections/test',{method:'POST',body:JSON.stringify({channelKey,connectionKey})})}
export async function testChannelPublish(channelKey:string,connectionKey:string,productId:string){return call<{ok:boolean;result?:unknown}>('/commerce/channel-connections/test-publish',{method:'POST',body:JSON.stringify({channelKey,connectionKey,productId})})}

export async function facebookTestPublish(connectionKey:string){return call<{ok:boolean;postId:string}>('/commerce/channel-connections/facebook-test-publish',{method:'POST',body:JSON.stringify({channelKey:'facebook_page',connectionKey})})}
export async function facebookDeleteTest(connectionKey:string){return call<{ok:boolean}>('/commerce/channel-connections/facebook-test-delete',{method:'POST',body:JSON.stringify({channelKey:'facebook_page',connectionKey})})}
export async function activateChannel(channelKey:string,connectionKey:string){return call<{ok:boolean}>('/commerce/channel-connections/activate',{method:'POST',body:JSON.stringify({channelKey,connectionKey})})}

export interface FacebookPageOption{id:string;name:string}
export async function listFacebookPages(connectionKey:string){return call<{ok:boolean;pages:FacebookPageOption[]}>('/commerce/channel-connections/facebook-pages',{method:'POST',body:JSON.stringify({connectionKey})})}
export async function selectFacebookPage(connectionKey:string,pageId:string){return call<{ok:boolean;page:FacebookPageOption}>('/commerce/channel-connections/facebook-select-page',{method:'POST',body:JSON.stringify({connectionKey,pageId})})}

export async function facebookPublishSelected(productId:string,connectionKeys:string[]){return call<{ok:boolean;results:Array<{connectionKey:string;postId:string;reused:boolean}>}>('/commerce/facebook/publish-selected',{method:'POST',body:JSON.stringify({productId,connectionKeys})})}
export async function facebookSyncProduct(productId:string){return call<{ok:boolean;results:unknown[]}>('/commerce/facebook/sync-product',{method:'POST',body:JSON.stringify({productId})})}

export async function listActiveFacebookPages(){return call<{pages:Array<{connectionKey:string;label:string;pageId:string|null}>}>('/commerce/facebook/active-pages')}

export type FacebookRotationStatus={settings:{enabled:boolean;dry_run:boolean;posts_per_product_per_week:number;min_page_gap_minutes:number;min_product_gap_hours:number;page_daily_budget:number;active_connection_keys?:string[];paused_connection_keys?:string[];last_generated_week?:string|null;last_generated_at?:string|null}|null;queue:Array<{id:string;product_id:string;connection_key:string;scheduled_at:string;rotation_no:number;template_id:string;status:string;post_id?:string|null;last_error?:string|null;product?:{id:string;sku:string;title:string;status:string;price:number}|null}>}
export async function getFacebookRotationStatus(){return call<FacebookRotationStatus>('/commerce/facebook/rotation-status')}
export async function updateFacebookRotationSettings(patch:{enabled?:boolean;dryRun?:boolean;activeConnectionKeys?:string[];pausedConnectionKeys?:string[]}){return call<{ok:boolean}>('/commerce/facebook/rotation-settings',{method:'PATCH',body:JSON.stringify(patch)})}

export type FacebookLearningDashboard={settings:{learning_enabled:boolean;learning_min_samples:number;learning_max_shift_minutes:number;learning_exploration_percent:number}|null;pageSummary:Array<{connectionKey:string;posts:number;collected:number;pending:number;avgReach:number|null;avgImpressions:number|null;avgEngaged:number|null}>;feedback:Array<{connection_key:string;template_id:string;local_dow:number;local_hour:number;samples:number;avg_reach:number|null;avg_impressions:number|null;avg_engaged:number|null;learning_score:number|null;eligible:boolean}>;ledger:Array<{connection_key:string;template_id:string;posted_at:string;local_hour:number;local_dow:number;impressions:number|null;reach:number|null;engaged_users:number|null;metric_status:string;metric_error?:string|null;measured_at?:string|null}>;health:{failed_jobs:number;stuck_jobs:number;metric_errors:number;metric_pending:number;last_posted_at:string|null}|null}
export async function getFacebookLearningDashboard(){return call<FacebookLearningDashboard>('/commerce/facebook/learning-dashboard')}
