create or replace function public.facebook_rotation_cancel_sold() returns integer language plpgsql security definer set search_path=public as $$ declare n integer; begin update public.facebook_rotation_queue q set status='SKIPPED_SOLD',last_error='STOCK_AUTHORITY_NOT_IN_STOCK',claim_token=null,next_attempt_at=null from public.products p where p.id=q.product_id and q.status in('PLANNED','CLAIMED','FAILED') and (p.status not in('ready_to_list','published','reserved') or p.one_availability is distinct from 'IN_STOCK'); get diagnostics n=row_count; return n; end $$;
create or replace function public.facebook_rotation_generate_week(target_date date default ((now() at time zone 'Asia/Bangkok')::date)) returns integer language plpgsql security definer set search_path=public as $$
declare wk text;monday date;inserted_count int:=0;p record;product_no int:=0;rot int;day_offset int;slot int;local_ts timestamp;page_key text;pages text[];daily_budget int;pick record;begin
monday:=target_date-(extract(isodow from target_date)::int-1);wk:=to_char(monday,'IYYY-IW');if exists(select 1 from public.facebook_rotation_queue where week_key=wk) then return 0;end if;
select active_connection_keys,least(coalesce(page_daily_budget,12),12) into pages,daily_budget from public.facebook_rotation_settings where id=true;if coalesce(array_length(pages,1),0)=0 then return 0;end if;
for p in select id from public.products where status in('ready_to_list','published','reserved') and one_availability='IN_STOCK' order by id loop for rot in 1..2 loop
page_key:=pages[((product_no+rot-1)%array_length(pages,1))+1];day_offset:=(product_no+case when rot=1 then 0 else 3 end)%7;slot:=((product_no/7)::int+case when rot=1 then 0 else 6 end)%daily_budget;
local_ts:=monday::timestamp+day_offset*interval '1 day'+case when slot<5 then time '11:30'+slot*interval '25 minutes' else time '18:30'+(slot-5)*interval '25 minutes' end;
select * into pick from public.facebook_learning_pick(page_key,extract(dow from local_ts)::smallint,extract(hour from local_ts)::smallint,'ROT-'||(((product_no+rot-1)%8)+1));if pick.reason='LEARNED' then local_ts=date_trunc('day',local_ts)+make_interval(hours=>pick.hour);end if;
if (select count(*) from public.facebook_rotation_queue q where q.connection_key=page_key and (q.scheduled_at at time zone 'Asia/Bangkok')::date=local_ts::date and q.status in('PLANNED','CLAIMED','POSTED'))<daily_budget and not exists(select 1 from public.facebook_rotation_queue q where q.product_id=p.id and q.status in('PLANNED','CLAIMED','POSTED') and abs(extract(epoch from(q.scheduled_at-(local_ts at time zone 'Asia/Bangkok'))))<172800) then insert into public.facebook_rotation_queue(product_id,connection_key,scheduled_at,week_key,rotation_no,template_id,status) values(p.id,page_key,local_ts at time zone 'Asia/Bangkok',wk,rot,pick.template_id,'PLANNED') on conflict do nothing;if found then inserted_count:=inserted_count+1;end if;end if;end loop;product_no:=product_no+1;end loop;
update public.facebook_rotation_settings set last_generated_week=wk,last_generated_at=now() where id=true;return inserted_count;end $$;
alter table public.facebook_rotation_settings add column if not exists alert_queue_stuck_minutes int not null default 15,add column if not exists alert_metric_error_threshold int not null default 3;
create or replace view public.facebook_rotation_health_v as select (select count(*) from public.facebook_rotation_queue where status='FAILED') failed_jobs,(select count(*) from public.facebook_rotation_queue where status='CLAIMED' and claimed_at<now()-interval '15 minutes') stuck_jobs,(select count(*) from public.facebook_learning_ledger where metric_status in('ERROR','UNAVAILABLE')) metric_errors,(select count(*) from public.facebook_learning_ledger where metric_status='PENDING') metric_pending,(select max(posted_at) from public.facebook_rotation_queue where status='POSTED') last_posted_at;